[package]
name = "a2d-unity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Unity serialized file and AssetBundle object graph reading."

[dependencies]
a2d-core.workspace = true
lz4_flex.workspace = true
