[package]
name = "a2d-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Transparent desktop host window."

[dependencies]
a2d-core.workspace = true
a2d-runtime.workspace = true
a2d-render.workspace = true
a2d-pack.workspace = true
